package com.pawmot.mtom.test.mtom;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-20T17:09:21.263+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://www.pawmot.com/MtomUpload_1_0/", name = "mtomUploadPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:21.263+02:00", comments = "Apache CXF 3.1.11")
public interface MtomUploadPortType {

    @WebMethod(action = "http://www.pawmot.com/MtomUpload_1_0/mtomUpload")
    @WebResult(name = "mtomUploadResponse", targetNamespace = "http://www.pawmot.com/MtomUpload_1_0/", partName = "response")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:21.263+02:00")
    public MtomUploadResponseType mtomUpload(
        @WebParam(partName = "request", name = "mtomUploadRequest", targetNamespace = "http://www.pawmot.com/MtomUpload_1_0/")
        MtomUploadRequestType request
    ) throws FaultMsg;
}
