package com.pawmot.mtom.test.b64u;

import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-20T17:09:20.933+02:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "Base64Upload_1_0", 
                  wsdlLocation = "file:/home/pawmot/Programming/jvm/mtom-test/src/main/resources/wsdl/Base64Upload_1_0.wsdl",
                  targetNamespace = "http://www.pawmot.com/Base64Upload_1_0/") 
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.933+02:00", comments = "Apache CXF 3.1.11")
public class Base64Upload10 extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.933+02:00")
    public final static URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.933+02:00")
    public final static QName SERVICE = new QName("http://www.pawmot.com/Base64Upload_1_0/", "Base64Upload_1_0");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.933+02:00")
    public final static QName Base64Upload10 = new QName("http://www.pawmot.com/Base64Upload_1_0/", "Base64Upload_1_0");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/pawmot/Programming/jvm/mtom-test/src/main/resources/wsdl/Base64Upload_1_0.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Base64Upload10.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/pawmot/Programming/jvm/mtom-test/src/main/resources/wsdl/Base64Upload_1_0.wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.933+02:00")
    public Base64Upload10(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.933+02:00")
    public Base64Upload10(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.933+02:00")
    public Base64Upload10() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.933+02:00")
    public Base64Upload10(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.933+02:00")
    public Base64Upload10(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.933+02:00")
    public Base64Upload10(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Base64UploadPortType
     */
    @WebEndpoint(name = "Base64Upload_1_0")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.933+02:00")
    public Base64UploadPortType getBase64Upload10() {
        return super.getPort(Base64Upload10, Base64UploadPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Base64UploadPortType
     */
    @WebEndpoint(name = "Base64Upload_1_0")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.933+02:00")
    public Base64UploadPortType getBase64Upload10(WebServiceFeature... features) {
        return super.getPort(Base64Upload10, Base64UploadPortType.class, features);
    }

}
