
package com.pawmot.mtom.test.b64u;

import javax.annotation.Generated;
import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-20T17:09:20.885+02:00
 * Generated source version: 3.1.11
 */

@WebFault(name = "fault", targetNamespace = "http://www.pawmot.com/Base64Upload_1_0/")
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.885+02:00", comments = "Apache CXF 3.1.11")
public class FaultMsg extends Exception {
    
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.885+02:00")
    private com.pawmot.mtom.test.b64u.Base64ServiceFaultType fault;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.885+02:00")
    public FaultMsg() {
        super();
    }
    
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.885+02:00")
    public FaultMsg(String message) {
        super(message);
    }
    
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.885+02:00")
    public FaultMsg(String message, Throwable cause) {
        super(message, cause);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.885+02:00")
    public FaultMsg(String message, com.pawmot.mtom.test.b64u.Base64ServiceFaultType fault) {
        super(message);
        this.fault = fault;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.885+02:00")
    public FaultMsg(String message, com.pawmot.mtom.test.b64u.Base64ServiceFaultType fault, Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2017-05-20T17:09:20.885+02:00")
    public com.pawmot.mtom.test.b64u.Base64ServiceFaultType getFaultInfo() {
        return this.fault;
    }
}
